topics:
  rgb: /depth_cam/rgb/image_raw
  depth: /depth_cam/depth/image_raw
  camera_info: /depth_cam/rgb/camera_info

yolo:
  model_path: /home/ubuntu/ros2_ws/day5_method_a/models/best.pt
  conf_thres: 0.25
  imgsz: 640

  # 如果你的模型只有一个目标类别，可以留空
  # 如果你明确知道类别名，比如 block / cube / PlasticBottle，可以填进去
  target_class_name: ""

depth:
  min_m: 0.05
  max_m: 3.00

  # 只在 bbox 中心区域取深度，避免边缘混入背景
  center_crop_ratio: 0.50

frames:
  base_frame_candidates:
    - base_link
    - robot/base_link

  camera_frame_candidates:
    - robot/link4/robot_cam_rgb
    - robot/link4/robot_cam_depth
    - depth_cam_frame
    - depth_cam_link
    - robot/depth_cam_frame
    - robot/depth_cam_link

runtime:
  timeout_sec: 10.0
  sync_slop_sec: 0.60
  output_json: /home/ubuntu/ros2_ws/day5_method_a/results/method_a_once.json
  output_debug_image: /home/ubuntu/ros2_ws/day5_method_a/results/debug/method_a_once.png
